### ISSUE TITLE
Problems in IE 11

### ISSUE THREAD

**Issue by code-chris** [halt-hammerzeit/libphonenumber-js#12]
Hi,
first, thanks for developing on this great library ;).

I detected a problem in Internet Explorer 11:
I get the following error if my App starts:
```
Unhandled rejection Error: Nicht genügend Stackspeicher.
   at __symbol:iterator0.51182658601296831.set (http://localhost/HelpdeskApp/assets/vendor.js:83134:12)
   at __symbol:iterator0.51182658601296831.set (http://localhost/HelpdeskApp/assets/vendor.js:83134:12)
   at __symbol:iterator0.51182658601296831.set (http://localhost/HelpdeskApp/assets/vendor.js:83134:12)
   at __symbol:iterator0.51182658601296831.set (http://localhost/HelpdeskApp/assets/vendor.js:83134:12)
   at __symbol:iterator0.51182658601296831.set (http://localhost/HelpdeskApp/assets/vendor.js:83134:12)
   at __symbol:iterator0.51182658601296831.set (http://localhost/HelpdeskApp/assets/vendor.js:83134:12)
   at __symbol:iterator0.51182658601296831.set (http://localhost/HelpdeskApp/assets/vendor.js:83134:12)
   at __symbol:iterator0.51182658601296831.set (http://localhost/HelpdeskApp/assets/vendor.js:83134:12)
   at __symbol:iterator0.51182658601296831.set (http://localhost/HelpdeskApp/assets/vendor.js:83134:12)
   at __symbol:iterat
```

This only happens in IE, not in Chrome. I think is is a problem with the metadata.min.json which cannot be handled or loaded from IE. Maybe it's too big.

I use Webpack 1 for Bundling the application.

Thanks for your investigation.

**Comment by halt-hammerzeit** [comment]
Hmm, "Not enough stack memory.".
This seems like a really deep recursion and IE having not that big call stack.
Tell me, what's on that line: `http://localhost/HelpdeskApp/assets/vendor.js:83134:12`.

**Comment by code-chris** [comment]
```
	      var descriptor = {
	        enumerable: false,
	        configurable: true,
	        get: get,
	        set: function set(value) {
	          setDescriptor(this, uid, {
	            enumerable: false,
	            configurable: true,
	            writable: true,
	            value: value
	          });
	          addInternalIfNeeded(this, uid, true);
	        }
	      };
```

This is the line: `setDescriptor(this, uid, {`

**Comment by halt-hammerzeit** [comment]
Hmm, dunno, this seems like some kind of transpiled Babel ES6 object properties.
You could also upload the whole vendor.dll

**Comment by halt-hammerzeit** [comment]
(seems that `setDescriptor` recurses for some reason)

**Comment by code-chris** [comment]
yes, I could send you the whole vendor.js tomorrow moring, when I'm at work again.

**Comment by code-chris** [comment]
@halt-hammerzeit You can see the full file here: 
https://gist.github.com/code-chris/9818a639b38eab113bab3f4d26771c29

**Comment by halt-hammerzeit** [comment]
Ok, seems that the code is the definition of `Object.getOwnPropertySymbols`.
So it can be some kind of `babel-polyfill` or another polyfill.
If it works without `libphonenumber-js` then I don't know what the reason is.

**Comment by halt-hammerzeit** [comment]
May be somehow related to that:
https://github.com/es-shims/get-own-property-symbols/issues/10

**Comment by halt-hammerzeit** [comment]
Make sure you have the latest versions of everything (maybe `rm -rf node_modules && npm install`).
I'm closing this for now.
