### ISSUE TITLE
npm browser-build fails

### ISSUE THREAD

**Issue by divick** [halt-hammerzeit/libphonenumber-js#13]
When I build using npm for browser, I get the following error log. I can send over npm-debug.log if needed.

```
> libphonenumber-js@0.2.30 browser-build /home/divick/work/external/libphonenumber-js
> WEBPACK_ENV=build webpack

/home/divick/work/external/libphonenumber-js/node_modules/webpack/lib/Compiler.js:324
					content = Buffer.from(content, "utf8");
					                 ^

TypeError: utf8 is not a function
    at Function.from (native)
    at Function.from (native)
    at Compiler.writeOut (/home/divick/work/external/libphonenumber-js/node_modules/webpack/lib/Compiler.js:324:23)
    at Compiler.<anonymous> (/home/divick/work/external/libphonenumber-js/node_modules/webpack/lib/Compiler.js:312:20)
    at /home/divick/work/external/libphonenumber-js/node_modules/webpack/node_modules/async/dist/async.js:3025:16
    at eachOfArrayLike (/home/divick/work/external/libphonenumber-js/node_modules/webpack/node_modules/async/dist/async.js:941:9)
    at eachOf (/home/divick/work/external/libphonenumber-js/node_modules/webpack/node_modules/async/dist/async.js:991:5)
    at Object.eachLimit (/home/divick/work/external/libphonenumber-js/node_modules/webpack/node_modules/async/dist/async.js:3089:3)
    at Compiler.emitFiles (/home/divick/work/external/libphonenumber-js/node_modules/webpack/lib/Compiler.js:301:20)
    at /home/divick/work/external/libphonenumber-js/node_modules/mkdirp/index.js:48:26
    at FSReqWrap.oncomplete (fs.js:82:15)

npm ERR! Linux 3.13.0-37-generic
npm ERR! argv "/home/divick/.nvm/versions/node/v5.0.0/bin/node" "/home/divick/.nvm/versions/node/v5.0.0/bin/npm" "run" "browser-build"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! libphonenumber-js@0.2.30 browser-build: `WEBPACK_ENV=build webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libphonenumber-js@0.2.30 browser-build script 'WEBPACK_ENV=build webpack'.
npm ERR! This is most likely a problem with the libphonenumber-js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     WEBPACK_ENV=build webpack
npm ERR! You can get their info via:
npm ERR!     npm owner ls libphonenumber-js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/divick/work/external/libphonenumber-js/npm-debug.log

```

**Comment by halt-hammerzeit** [comment]
https://github.com/webpack/webpack/issues/3930
You are probably using the newest Webpack and Node.js 4.x

**Comment by egoroof** [comment]
@divick as you use Nodejs 5.x then you need to update it to 5.10+

**Comment by divick** [comment]
@egoroof Installing node 5.10.1 seems to work. Thanks for your help.
